import { test, expect } from '@playwright/test';
import path from 'node:path';

test('SOC CSV workflow with mandatory password change', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/login');
  await page.getByLabel('Usuario', { exact: true }).fill(process.env.E2E_USERNAME!);
  await page.getByLabel('Contraseña', { exact: true }).fill(process.env.E2E_PASSWORD!);
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await expect(page.getByText('Cambio de contraseña obligatorio')).toBeVisible();
  await page.getByPlaceholder('Contraseña actual').fill(process.env.E2E_PASSWORD!);
  await page.getByPlaceholder('Nueva contraseña (mín. 8 caracteres)').fill(process.env.E2E_NEW_PASSWORD!);
  await page.getByPlaceholder('Confirmar nueva contraseña').fill(process.env.E2E_NEW_PASSWORD!);
  await page.getByRole('button', { name: 'Cambiar contraseña', exact: true }).click();
  await expect(page.getByText('Cambio de contraseña obligatorio')).toHaveCount(0);
  const watcher = await page.context().newPage();
  await watcher.goto('/dashboard');
  await expect(watcher.getByText('Total de eventos', {exact:true})).toBeVisible();
  const refresh = watcher.waitForResponse(r => r.url().endsWith('/analytics/summary') && r.status() === 200);
  await page.goto('/import');
  await page.locator('input[type=file]').setInputFiles(path.resolve('../data/sample_events_1.csv'));
  await page.getByRole('button', { name: 'Importar y analizar' }).click();
  await expect(page.getByText(/Insertados: 46/)).toBeVisible();
  expect((await (await refresh).json()).total_events).toBe(46);
  await expect(watcher.getByText('46', {exact:true}).first()).toBeVisible();
  await watcher.close();
  await page.getByRole('button', { name: 'Ir al Dashboard' }).click();
  await expect(page.locator('.recharts-surface').first()).toBeVisible();
  await page.screenshot({path:testInfo.outputPath('dashboard.png'),fullPage:true});
  await page.goto('/events');
  await expect(page.locator('tbody tr').first()).toBeVisible();
  const search = page.locator('input').first();
  await search.fill('NO_SUCH_EVENT_unique');
  await expect(page.getByText('No se encontraron eventos', {exact:true})).toBeVisible();
  await search.fill('');
  await expect(page.locator('tbody tr').first()).toBeVisible();
  await page.locator('tbody tr').first().click();
  await expect(page.getByText('Detalle del Evento', {exact:true})).toBeVisible();
  await page.screenshot({path:testInfo.outputPath('event-detail.png'),fullPage:true});
  for (const route of ['correlations','timeline','mitre','geoip','graph','reports','history','settings']) {
    await page.goto('/'+route);
    await expect(page.locator('main h2').first()).toBeVisible();
  }
  await page.getByLabel('Entidad de reportes programados').fill('Scheduled E2E');
  await page.getByRole('button', {name:'Guardar programación'}).click();
  await expect(page.getByText('Programación guardada')).toBeVisible();
  await page.getByRole('button', {name:'Ejecutar ahora'}).click();
  await expect(page.getByText(/Ejecución .*completed/)).toBeVisible();
  await page.goto('/reports');
  await page.getByPlaceholder('Nombre del cliente').fill('Visual E2E');
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Generar y descargar' }).click();
  expect((await download).suggestedFilename()).toMatch(/\.pdf$/);
  await page.goto('/history');
  await page.getByRole('button', { name:'Reportes', exact:true }).click();
  await expect(page.getByText(/Visual E2E/)).toBeVisible();
  await page.screenshot({path:testInfo.outputPath('history.png'),fullPage:true});
  await page.getByRole('button', { name:/Cerrar sesión/i }).click();
  await expect(page.getByRole('button', {name:'Iniciar sesión'})).toBeVisible();
  expect(errors).toEqual([]);
});
